### PR TITLE
Cleanups, add --config argument

### PR DESCRIPTION
**Pull request by jleclanche**

### CODE REVIEW

**Comment by freiheit** [comment]
Please have a little patience with me...  I want to look over each of these before merging. I skimmed through and most look like very nice improvements that make this project start to look like an actual Python programmer was involved in it (but I can still readily follow what's going on).

I do want to be careful with the timezone handling and give that a very careful look. There's some real craziness about getting timezone stuff to work properly on both Unix and Windows.

**Comment by freiheit** [comment]
Ooops, just meant to "approve" one commit, not the whole batch...

**Comment by jleclanche** [comment]
The timezone commit should be functionally identical, it just simplifies the logic by removing some unnecessary calls in the debug, by making the timezone a global setting and cleaning up extract_best_item_date()

**Comment by freiheit** [comment]
Thank you!

**Pull request merged**
